/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: ab9ec3ce3ce718213bf5eb78bd5726ba)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	GOOGLE_CLIENT_ID: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
	interface StagingEnv {
		DB: D1Database;
		ASSETS: Fetcher;
		GOOGLE_CLIENT_ID: string;
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GOOGLE_CLIENT_ID" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET">> {}
}
